package com.evernym.extension.agency.common


object Constants {

  val AGENT_CORE_ACTOR_SYSTEM_NAME = "agent-core"

  val ACTOR_TYPE_AGENCY_AGENT_ACTOR = 3

  val ACTOR_TYPE_AGENCY_AGENT_PAIRWISE_ACTOR = 4

  val MSG_TYPE_FWD = "fwd"

  val MSG_TYPE_AGENT_CREATED = "AGENT_CREATED"

  val MSG_TYPE_CREATE_PAIRWISE_KEY = "CREATE_PAIRWISE_KEY"

  val MSG_TYPE_PAIRWISE_KEY_CREATED = "PAIRWISE_KEY_CREATED"

  val MSG_TYPE_GET_OWNER_AGENT_DETAIL = "GET_OWNER_AGENT_DETAIL"

  val MSG_TYPE_OWNER_AGENT_DETAIL = "OWNER_AGENT_DETAIL"

}
